atom/language-javascript

grammars/javascript.cson

In ES6 was created new 'for of' cycles

Highlighting 'of' as operator for 'for of' cycles

---

grammars/javascript.cson

https://github.com/atom/language-javascript/issues/90
This change can fix part of this bug.

Part of fix issue #90

---

snippets/language-javascript.cson

Proposal for adding "CommonJS require" snnipet

---

snippets/language-javascript.cson

Snippets for anonymous and named generators.

Added snippets for generator

---

snippets/language-javascript.cson

Added var and multiple cursor selection into forin snippet

---

grammars/javascript.cson

Fixed issue
https://github.com/AMalininHere/language-javascript-better/issues/13

Fixed import meta block

---

grammars/javascript.cson
spec/javascript-spec.coffee

ES7 async functions. [#106](https://github.com/atom/language-javascript/issues/106)

Added support of async functions

---

grammars/javascript.cson
spec/javascript-spec.coffee

Added support for params in arrows

---

grammars/javascript.cson

Fix dollar sign prefixed support classes

---

grammars/javascript.cson
spec/javascript-spec.coffee

This will fix issue https://github.com/atom/language-javascript/issues/113

Fixed broken highlighting for comments inside function parameters

---

snippets/language-javascript.cson

Properly escape the setTimeout snippet

---

grammars/javascript.cson
spec/javascript-spec.coffee

This might be a naive change, but it's the first thing I tried and it worked :P.
Fixes #175

Give priority to strings in functions

---

grammars/javascript.cson
spec/javascript-spec.coffee

Make sure `of` and `in` aren't part of a larger word

---

grammars/javascript.cson
spec/javascript-spec.coffee

I had to move the group down because `/` started to override the regex group.
Fixes #212

Fix / not being tokenized as an operator

---

grammars/javascript.cson
spec/javascript-spec.coffee

Scope constructor to entity.name.function.constructor

---

grammars/javascript.cson
spec/javascript-spec.coffee

Fixes https://github.com/atom/language-javascript/issues/221
/cc @50Wliu @atom/feedback

Tokenize correctly when assigning arrow function as object property

---

grammars/javascript.cson
spec/javascript-spec.coffee

Don't tokenize as 'import' after ';'

---

grammars/javascript.cson
spec/javascript-spec.coffee

Fix ES6 default object export 

---

README.md

I'm sorry for the utter overkill of dropping a pull request in your lap, but awkward sentence structure really gives me the irrits.
>  to JavaScript __file__ in Atom
That's been sitting there for nearly two years.

Reword opening line of readme file

---

grammars/javascript.cson
spec/javascript-spec.coffee

Tokenize spread operator

---

grammars/javascript.cson

Reverts atom/language-javascript#284

Revert "Added delete token"

---

grammars/javascript.cson
spec/javascript-spec.coffee

See [#309 (comment)](https://github.com/atom/language-javascript/issues/309#issuecomment-174328919)

Tokenize built-in variables with properties

---

grammars/javascript.cson

It's just a little change of a part of exactly one line of one file, I find no problems to merge this.
Also, if someone reminds me to add specs for this, please consider this pull request as a feature request.

Add 'WeakSet' and 'WeakMap' to '.support.class.js'

---

grammars/javascript.cson
spec/javascript-spec.coffee

Fix regex in arrow function

---

snippets/language-javascript.cson

Part of #345 
Reference: http://airbnb.io/javascript/#13.1

Declare Required Modules As Const Instead Of Var

---

grammars/javascript.cson
spec/javascript-spec.coffee

Fixes #356

---

grammars/javascript.cson

Highlight performance object from the [High Resolution Time API](https://www.w3.org/TR/hr-time/).

Add performance highlighting.

---

grammars/javascript.cson
spec/javascript-spec.coffee

Closes #326 (actually was fixed by #311)

Improve objects, properties

---

spec/javascript-spec.coffee

Don't treat function calls as constant

---

grammars/javascript.cson
spec/javascript-spec.coffee

Fixes #354
Maybe @kartikanand knowns a better solution
Refs #355
Refs #344 (wrong scopes with `$`)

Fix console, Math matching

---

grammars/javascript.cson
spec/javascript-spec.coffee

Allow brackets in regex

---

snippets/language-javascript.cson

I couldn't find an issue where this simple addition was discussed, so I figured having this PR is alright.

add arrow function snippet

---

spec/javascript-spec.coffee

Closes #457
/cc @DamnedScholar

Properly test HTML template strings

---

grammars/javascript.cson

Add stringify to support.function.js

---

grammars/javascript.cson

Add JScript file extensions .jscript and .jse
https://github.com/search?utf8=%E2%9C%93&q=function+extension%3Ajscript
https://github.com/search?utf8=%E2%9C%93&q=function+extension%3Ajse

Add JScript extensions

---

.gitignore
grammars/tree-sitter-regex.cson
lib/main.js
package.json

Add a new language, `regex`, an injection point for that new language (regex literals), and styling for regex constructs.
Syntax highlighting within regexes!

Inject regexps

---

grammars/tree-sitter-javascript.cson
grammars/tree-sitter-regex.cson
package.json

Refs https://github.com/atom/atom/pull/17881

Replace id and legacyScopeName with scopeName

---

grammars/tree-sitter-javascript.cson
package.json

Bump tree-sitter-javascript and adjust scope mapping for new_expression

---

package.json

This updates the tree-sitter packages to 0.16.0
Improvements:
https://github.com/tree-sitter/tree-sitter-javascript/compare/v0.15.2...v0.16.0
https://github.com/tree-sitter/tree-sitter-jsdoc/compare/v0.15.2...v0.16.0
https://github.com/tree-sitter/tree-sitter-regex/compare/v0.15.1...v0.16.0

update tree-sitter packages to 0.16.0

---

grammars/javascript.cson
spec/javascript-spec.coffee

tokenize numeric separators
numeric separators will be tokenized
none
fixes #669

fix: add numeric separators

---

package.json

My operators pr is almost not blocked now!
Updates dependencies to the latest version
Updates dependencies (to a version that supports more operators)
(none)
Blocks #686

⬆️ update tree-sitter packages to 0.19.0

---

.github/workflows/ci.yml

Based off https://github.com/atom/github/commit/9207c7b2a793327ae26b71f50fde4e63c50e9c5f
Remove windows-build installation step
The windows ci tests are failing. Based off the similar error fixed by https://github.com/atom/github/commit/9207c7b2a793327ae26b71f50fde4e63c50e9c5f
fixes window
fixes #696
will probably cause #695 and #698's tests to pass

Remove windows-build installation step
