atom/language-javascript

settings/language-javascript.cson
As a follow-up to #77, where @jbt commented:
>  I'd contend that the ]) shouldn't be automatically indented
This adds autoindent rules for arrays, like:
```js
var pets = [
'kitten',
'fish'
];
```
If not auto-indenting arrays was a conscious decision, please feel free to close!
=> Autoindent rules for arrays

grammars/javascript.cson
Add support for files with a shebang like `#!/usr/bin/env iojs`
Fixes #100
=> Match iojs shebangs

grammars/javascript.cson
added the `from` keyword, used in ES6 import statements.
```js
import foo from './bar.js';
```
=> added `from` to the regex matching `keyword.control.js`

grammars/javascript.cson
On OSX Yosemite 10.10, AppleScripts can be written in JavaScript language and are interpreted using JavaScriptCore + a Cocoa bridge.
Such scripts can be launched via a [shebang](https://github.com/dtinth/JXA-Cookbook/wiki/Using-JavaScript-for-Automation#creating-a-shebang-script) in the first line and stashed in ~/bin.
This commit makes these JS-format AppleScripts read out as JS code in atom.
```
>>> '#!/usr/bin/osascript -l JavaScript'.match('^#!.*\\b(node|iojs|JavaScript)')
#!/usr/bin/osascript -l JavaScript,JavaScript
```
=> :apple: match on shebangs of JS-syntax AppleScripts

snippets/language-javascript.cson
Reason: majority of snippets use single quotes in them.
Also it should probably be configurable which type of quotes will be used (not sure if there is some ticket for that).
=> Unified quotes in snippets

snippets/language-javascript.cson
And renamed parameter in try catch snippet from variable to e
Preview (old behavior at the top, new at the bottom)
=> Removed useless statement variables from try snippet

grammars/javascript.cson, spec/javascript-spec.coffee
The following cases will be properly recognized:
```javascript
Class.method = function nonAnonymous() {}
this.method = function nonAnonymous() {}
foo: function name() {}
```
Also added test case for fixed cases.
This PR fixes https://github.com/github/linguist/issues/2284.
=> :bug: Fix tokenization for anonymous functions

grammars/javascript.cson
Javascript file extensions for SAP HANA XS engine, see http://help.sap.com/hana/SAP_HANA_XS_JavaScript_Reference_en.pdf
Already part of https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
=> Extensions xsjs + xsjslib

grammars/javascript.cson, spec/javascript-spec.coffee
Highlighting of ES6 methods(functions without `function` keyword).
See [in sublime](https://github.com/babel/babel-sublime/blob/master/JavaScript%20%28Babel%29.tmLanguage#L1987)
=> Added methods support

grammars/javascript.cson, spec/javascript-spec.coffee
Things like `MY_COOL_VAR` are now tokenized under `constant.other.js` (which could be `constant.other.global.js`, wasn't sure which one was best).  Also be aware I'm not too familiar with JS so this PR could totally be on the wrong track.
First time I managed to get a language spec I wrote to pass :smile:.
Refs #137.
=> Tokenize ALL_CAPS variables

grammars/javascript.cson, spec/javascript-spec.coffee
The `myCoolVar` in `const myCoolVar = 42` will now be tokenized as a constant.
Unfortunately this doesn't affect tokenization after the declaration...
```js
const myCoolVar = 42;  //Works!  constant.other.js
var something = 0;
something = myCoolVar * 1;  //Doesn't work :(
```
Again, refs #137.  Also, cc @kevinsawicki.
=> Tokenize variables declared using const as constants

grammars/javascript.cson, spec/javascript-spec.coffee
The construction `{,2}` in regular expressions is only supported by Oniguruma (which is used by Atom). This Atom bundle is used to highlight JavaScript code on GitHub. However, GitHub is using a [PCRE-based engine](https://github.com/vmg/pcre) for regexes and thus, the following code gets incorrectly highlighted.
```javascript
addLinter("E014", function lintColParentsAreRowsOrFormGroups($, reporter) {
var selector = COL_CLASSES.map(function (colClass) {
return '*:not(.row):not(.form-group)>' + colClass + ':not(col):not(th):not(td)';
}).join(',');
var colsOutsideRowsAndFormGroups = $(selector);
if (colsOutsideRowsAndFormGroups.length) {
reporter("Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s", colsOutsideRowsAndFormGroups);
}
});
```
This pull request fixes that by …
=> Explicit count modifiers

grammars/javascript.cson, spec/javascript-spec.coffee
Previous, `:` was not scoped at all for object functions.
```javascript
var a = {
hello: 'testing',
foo: function() {},
"testing": function() {}
}
```
The `:` in `foo: function() {}` and `"testing": function() {}` had no scope originally. This PR scopes the `:` to `keyword.operator.js` to match the scope of other `:` in objects.
=> Fix not tokenizing operators in object functions

grammars/javascript.cson, spec/javascript-spec.coffee
As described in https://github.com/atom/language-javascript/issues/164 this pull request will add support for `@mixins`.
=> Add @mixins to jsdoc

grammars/javascript.cson
`.jsm` files are Javascript modules used by Firefox and extensions:
https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules
=> Adding JSM file as an extension

grammars/javascript.cson, spec/javascript-spec.coffee
E.g. `new $thing()` 
It will now mark $thing as an instance constructor.
=> Correctly mark $ prefixed vars as instance constructors

grammars/javascript.cson, spec/javascript-spec.coffee
I am tired of how the syntax highlighting of constant identifiers breaks when the `const` keyword is combined with destructuring assignment.
This is the current behaviour:
Behaviour as of this PR:
I would additionally like `d` to be properly highlighted as a constant above, but that will have to wait.
=> Add support for destructuring in const assignments

grammars/javascript.cson, spec/javascript-spec.coffee
My new `const` matchers broke regex highlighting (and possibly others). This PR addresses #176.
Before:
After
=> Fix highlighting issue when declaraing a const regex variable

grammars/javascript.cson, spec/javascript-spec.coffee
Made a const declaration end with one of `=, of, in, ;`. 
Fixes #180
Before:
After:
=> Make =, of, in and ; end a const declaration.

grammars/javascript.cson, spec/javascript-spec.coffee
Continuation of #181.
I also removed some unneeded whitespace matchers so that `const` gets highlighted the moment you finish typing it, not after you add a space (this is consistent with all the other regex rules).  There was also an orphaned whitespace matcher without a name, so I :fire:'d that as well.
/cc @Victorystick
=> More const fixes

spec/javascript-spec.coffee
Nothing much to see here.  Now there shouldn't be any dangling `it`s under the main `describe "Javascript grammar"` block.
There's now also some consistency with whether or not there's a newline after `{tokens}` (I've made it so there isn't one).
=> Clean up specs file

grammars/regular expression replacement (javascript).cson, spec/regular-expression-replacement-spec.coffee
This pull request adds support for highlighting regular expression replacement strings. Specifically it was created to support atom/find-and-replace#494 , adding syntax highlighting to the replacement editor of the find-and-replace dialog.
While this pull request does not (at this time) include support in-line tokenizing of the replacement strings within a Javascript source file, it could serve as the basis for that further work.
=> Add regexp replacement grammar

snippets/language-javascript.cson
The closing bracket of the $3 tabstop wasn't highlighted properly on tab.
=> Fix highlighting bug in the 'for in' snippet

snippets/language-javascript.cson
It looks like there was some confusion about the `\\` at 8d915f14914fd39a6a2c4896562e3dae8c94b500 (`setInterval` and `setTimeout` has already been fixed).
=> Fix bracket highlighting in the 'try' snippet

grammars/javascript.cson, spec/javascript-spec.coffee
The first commit completes the fix for #70 (a3c3a07be56). Function arguments can now contain line comments.
The second commit fixes an issue reported in #137:
```js
import {x, y} as p from 'point';  // fixed in second commit
function test(arg1 = 0, // fixed in first commit
arg2 = 1, arg3) {
}
```
See the [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2F184dfc47c63cfc26cb4a79c41a11d8394aacd3bd%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=&code=import+{x%2C+y}+as+p+from+%27point%27%3B++%2F%2F+fixed+in+second+commit%0D%0Afunction+test%28arg1+%3D+0%2C+%2F%2F+fixed+in+first+commit%0D%0A++++++arg2+%3D+1%2C+arg3%29+{%0D%0A}).
=> Improve support for line comments

grammars/javascript.cson, spec/javascript-spec.coffee
This pull request implements a change requested in #58.
Currently unescaped multiline strings are highlighted as if they were correct:
```js
'line1
line2\
line3'
```
This change will highlight such strings as invalid.
[Example of an invalid string with this change in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2Fa906d863677b8346aba3d429434a63747ac334ba%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=&code=%27line1%0D%0Aline2\\%0D%0Aline3%27).
/cc @Cydrobolt
=> Highlight unescaped multiline strings as invalid

grammars/javascript.cson, spec/javascript-spec.coffee
=> Follow naming conventions

grammars/javascript.cson, spec/javascript-spec.coffee
This commit expands es6 fat arrow support by adding syntax highlighting to stored fat arrow function declarations.
Before:
After (foo and bar are tokenized):
=> Add support for stored arrowed function syntax highlighting

grammars/javascript.cson, spec/javascript-spec.coffee
Reverts atom/language-javascript#206
Atom specs will take some time to be updated.  In addition, it would be best to get the new standards written up before making any changes.  This (hopefully temporary) revert allows us to keep making other improvements to language-javascript.
=> Revert "Follow naming conventions"

grammars/regular expression replacement (javascript).cson, spec/regular-expression-replacement-spec.coffee
At least in Firefox, Chrome, and the Atom Find-and-Replace, $0 and $00 are
treated as plain string values while $& is used as the variable to hold the
full match.
This commit updates the replacement grammar to only allow integers 1-99,
with and without a leading 0.
Here is the new behavior in Atom Find-and-Replace:
=> Stop tokenizing $0 and $00 as replacement variables.

grammars/javascript.cson, spec/javascript-spec.coffee
Also adds some more support functions and adds some safeguards (eg `.log()` isn't valid anymore and neither is `console.log` - it has to be `something.log()`).
Fixes #213
=> Isolate periods in console methods

grammars/javascript.cson, spec/javascript-spec.coffee
In the expression `a ? /b/ : /c/`, the first regexp wasn't recognized as such, but was tokenized as a sequence of operators instead. This fixes it by allowing regexp to immediately follow the `?` operator.
This fixes the syntax highlighting issue in Atom as well as on GitHub.com that manifests itself like this:
This is related to #93
=> Allow regexp to immediately follow `?` ternary operator

grammars/javascript.cson, spec/javascript-spec.coffee
Supports proper tokenizing of these keywords when they appear as subexpression `b` within ternary expression `a ? b : c`:
yield, true, false, null, [CONSTANT], super, this, debugger,
module, exports, __filename, __dirname, global, process
They are not tokenized because there was a rule that these keywords should not be followed by `:`. This was to compensate for JS key/value syntax `{ foo: bar }`.
The fix adds an alternate pattern for each of these keywords that explicitly allows these keywords to be followed by `:` if they were preceded by `?`.
Fixes #93
=> Fix tokenizing of various keywords within ternary expression

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes #232
```js
export var x = 0;
export const CONSTANT = 0;
export let scopedVariable = 0;
export function func(p1, p2){}
export class Foo {}
export { bar };
export { bar, foo as alias };
export default "string";
export default 123 + 23;
export default name;
export default function () {}
export default function func() {}
export default class {}
export default class Foo {}
export { foo as default };
export { name } from 'module-name';
export * from 'module-name';
export { default as alias } from 'module-name';
export { default as alias }; //illegal
export { name as * }; //illegal
import "module-name";
import * as name from "module-name"
import defaultMember from "module-name";
import { member } from "module-name";
import { default as defaultMember } from "module-name";
import { member1 , …
```
=> ES6 import export

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes #199.  Also includes some very minor style fixes.
In the future I'd like to combine all the `meta.brace.*.js` patterns into their own `braces` block, but that was too much work for this.
/cc @schmittyjd, @methodgrab
=> Capture regular braces before ending interpolation

grammars/javascript.cson, spec/javascript-spec.coffee
Self-explanatory.  Only the arrow itself should be captured.
=> Don't capture whitespace as `storage.type.arrow.js`

grammars/javascript.cson
This pull requests adds support for `.jscad` files to have JavaScript syntax highlighting. This closes #247.
=> Add support for OpenJsCad

grammars/javascript.cson, spec/javascript-spec.coffee
To properly tokenize arguments, functions' declarations (anything else?) should be tokenized first
Atom specs should be reverted as well...
Ref: #224 (Recognize function bodies)
=> Revert argumetns matching

grammars/javascript.cson
Hi there,
It'd be nice for Atom to recognize [`.json5` files](https://github.com/aseemk/json5) and syntax highlight them. Doing so as JavaScript is good enough — and is in fact what GitHub does too:
https://github.com/github/linguist/blob/c8b30a62f9caf50609e4abc515469a5dda9b9584/lib/linguist/languages.yml#L1581-L1586
I'm not sure if what I've done in this PR is the best way to achieve this, though. Please feel free to let me know if I should do it differently. For now, I did the same thing I did for `._js` (pull #4).
Thanks!
=> Support JSON5 files

grammars/javascript.cson, spec/javascript-spec.coffee
#206 is back! :tada:
Tested my changes locally and I *think* I can get everything working this time (it's hard to tell because I get ~50 spec failures on atom/atom).  Will be pushing PRs to language-html and atom shortly.
/cc @atom/languages @slinto
Actually fixes #201
=> Tokenize let and var as storage.type.var.js

snippets/language-javascript.cson
...this wasn't supposed to be both the exports and the case snippets. But it appears GitHub added both anyway.
But basically, adds the 'case' and the 'exports' snippet.
=> Add exports & case snippet.

grammars/javascript.cson
Added delete token as noted [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete)
=> Added delete token

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes #304
I made similar changes in [atom/language-c#107](https://github.com/atom/language-c/pull/107#issuecomment-167242191)
=> Tokenize round brackets correctly

grammars/javascript.cson
Google Apps Script is a Javascript based scripting language for the Google Apps platform. Gs is the file type used.
=> Add auto detection for Google Apps Script

grammars/javascript.cson, spec/javascript-spec.coffee
[Tagged template strings](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings) allow embedding HTML and CSS in a JavaScript file, but allow a safe way to escape the values provided by the JavaScript context, and allows a [tool to statically verify the use of this pattern](https://github.com/mozfreddyb/eslint-plugin-no-unsafe-innerhtml).
Since tagged template strings provide a name for the function used to process the template string, that name can be used to target using HTML or CSS syntax highlighting within a template string.
This pull request enables tagged string use whose tag function name ends in `html` to specify HTML syntax highlighting inside the string. Same with `css`.
There are cases where the interpolated_js loses out to the …
=> Support HTML and CSS syntax in template strings suggesting those formats

grammars/javascript.cson, spec/javascript-spec.coffee
```js
// octal
015, 0010, 0o77, 0O10
// hexadecimal
0xFF, 0xff, 0x1123, 0X00111, 0XF1A7
// binary
0b11, 0b0011, 0b11,                 
// decimal
// [(+|-)][digits][.digits][(E|e)[(+|-)]digits]
1E+12
3.1415926
.123456789
3.1E+12
.1e-23
1
1.
.1
1.1
1E+3
1.E3
.1E+3
1.1E+3
// illegal identifiers
1abc
123abc
1$
123$abc
.1a
obj.1
obj.1a
1$.123
```
Fixes #318
=> Don't scope decimals as illegal; tokenize decimal marks, illegal identifiers

grammars/javascript.cson, spec/javascript-spec.coffee
This pull request adds grammar parsing for JSDoc variable type, variable name and description:
```js
/**
* This is a title
* @param {object} context this is a description
*/
```
... in which `{object} context this is a description` is now inside the scope of `other.meta.jsdoc`, `{object}` is `entity.name.type.instance.jsdoc`, `context` is `variable.other.jsdoc` and `this is a description` `other.description.jsdoc`.
=> Add grammar to parse JSDoc variable type, variable name and description

grammars/javascript.cson, spec/javascript-spec.coffee
- Update [Math](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math) methods and properties to ECMAScript 2015.
- Separate Math methods/properties from others so that they are only highlighted when preceded by the Math object (e.g. highlight `Math.random()` but not `foo.random()`).
- Add Math unit tests.
=> Update Math highlighting.

grammars/javascript.cson, spec/javascript-spec.coffee
This pull request adds a rule to highlight GraphQL inside `Relay.QL` template strings. 
As of https://github.com/github/linguist/pull/2947 we have a GraphQL grammar in Linguist.
cc @kevinsawicki @arfon @kdaigle @gjtorikian
=> Highlight GraphQL inside Relay.QL template strings

grammars/javascript.cson, spec/javascript-spec.coffee
Changed class name scope from `entity.name.type.js` to `entity.name.type.class.js`. This is consistent with the `entity.name.type.class.java` scope used in the Java package.
This allows syntax themes to style class names without affecting other scopes that also contain `entity.name.type`, like `entity.name.type.instance.js`.
=> Fix class name highlighting.

grammars/javascript.cson, spec/javascript-spec.coffee
Current highlighting doesn't understand const destructuring when the _first variable_ isn't placed on the same line as the `const`. The same rule applies recursively for subobjects.
```js
// works for `a` here
const { a,
b: {
c, // doesn't work for `c` or `d`
d,
},
} = foo;
const { a,
b: { c, // works for `c` and `d`
d,
},
} = foo;
// no variables highlighted
const {
a,
b: {
c,
d,
},
} = foo;
```
With these changes:
=> Improve multiline const destructuring

grammars/javascript.cson, spec/javascript-spec.coffee
To properly sort it out, it would mean modifying the CSS parsing in language-css, and even then may be hard to do given that curly braces are an integral part of the CSS format.
=> Fixes #338: source.css parsing conflicts with CSS template parsing

grammars/javascript.cson, spec/javascript-spec.coffee
```js
constructor(args)
{
this.noHighlighting; // :(
}
```
Also bring it in line with the new function tokenization syntax.
=> Fix constructor body not being highlighted

grammars/javascript.cson, spec/javascript-spec.coffee
1. `arguments` now uses `variable.language` like `this` and `super`, since it's scoped identically, and it's normally treated as a keyword in practice, not a traditional variable (even though it's technically a valid identifier).
2. The `extends` clause of classes now uses `entity.other.inherited-class`, like in the language packages for many other OO languages (e.g. Java, Scala, Ruby).
=> Style `arguments` like `this`, style superclass name distinctly

grammars/javascript.cson
Since it exists in official JSDoc dictionary :
* http://usejsdoc.org/tags-public.html
=> Add @public docblock match in Javascript grammar

grammars/javascript.cson
Add the missing [JSDoc tags used by Closure Compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler) that were not already in the list. This PR ensures that all JSDoc tags in the below sample are properly highlighted.
```js
/**
* A reference to the class {@code Class} followed by the JSDoc
* tags understood by Closure Compiler.
*
* @abstract
* @const
* @constructor
* @define
* @deprecated
* @dict
* @enum
* @export (currently only @exports supported)
* @extends
* @final
* @implements
* @inheritDoc (currently only @inheritdoc supported)
* @interface
* @lends
* @license / @preserve
* @nocollapse
* @nosideeffects
* @override
* @package
* @param
* @private
* @protected
* @record
* @return
* @struct
* @template
* @this
* @throws
* @type
* @typedef
* @unrestricted
*/
```
=> Add missing JSDoc tags used by Closure Compiler

grammars/javascript.cson
`from` is not a reserved word
```js
from = 123 // shouldn't be highlighted as a keyword
abc = 123
```
Fixes #377
=> 🐛  Allow 'from' as identifier

grammars/javascript.cson
=> Allow multiple spaces in JSDoc tags

grammars/javascript.cson
This pull request extends the list of methods recognized as being part of the DOM. The original list was very incomplete and led to peculiar behaviour such as classList.add() and classList.remove() being coloured differently.
These additions were collected by iterating through several common DOM interfaces, mainly in Firefox and Chrome. For practical reasons it is by no means complete, but I believe it covers those which are most-used. Intentional omissions include prefixed properties and non-standard properties with little adoption. I also removed a couple of overlapping properties from the support.function.js regex.
=> Extend list of DOM methods

grammars/javascript.cson, spec/javascript-spec.coffee
Some values don't receive their usual highlighting when used inside a case statement:
Not all of these statements are valid JavaScript (e.g., `case debugger:`), but authors should probably be reminded of a keyword's significance through highlighting.
=> Fix missing highlighting in case statements

grammars/javascript.cson, spec/javascript-spec.coffee
```js
a = {
constructorABC: {}
};
```
Fixes #391
=> 🐛  Fix 'constructor' boundary

grammars/javascript.cson, spec/javascript-spec.coffee
This PR adds improved support for JSDoc highlighting of `@return` and `@returns`. Currently the first word of a description will incorrectly take on the scope of a variable (an element that the `@returns` doesn't have http://usejsdoc.org/tags-returns.html)
Before:
After:
Also took the opportunity to tidy up the JSDoc code a bit.
=> Add improved JSDoc support for @returns

grammars/javascript.cson
Trivial changes to code formatting that were prompted [by feedback to an earlier PR](https://github.com/atom/language-javascript/pull/405#issuecomment-241066868).
Summary:
--------------
* Simplified character classes for matching variable names:
```
[a-zA-Z_$][a-zA-Z_$0-9]*
[a-zA-Z_$][\\w$]*
```
* Extended patterns now use triple-quoted blocks consistently
* Lengthy patterns converted into extended patterns to clarify
=> Clean up grammar source

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes #406 by using begin/end matching for ternary expressions
```js
result = condition ? something : (a, b) => a + b
```
Fixes #279 by matching case statements only in switch block (replaces #405 fix)
```js
switch (foo())
{
case 'string':
case a:
case a + b:
case foo(bar):
case ABC:
case 123:
foo(bar)
break;
case null:
case true:
default:
}
case abc: // won't be highlighted
```
=> Fix arrow functions inside ternary expressions

grammars/javascript.cson, spec/javascript-spec.coffee
[#334 (comment)](https://github.com/atom/language-javascript/issues/334#issuecomment-219531841)
```js
// highlights the contents of the string correctly as a string:
{ func: 'function foo() { return "foo"; }' };
"things are ok";
// now it thinks the string contents are actually a function definition:
{ function: 'function foo() { return "foo"; }' };
"not ok... :("
```
Fixes:
```js
foo: a => a
foo : a => a // bug
```
=> Fix function keyword as property name

grammars/regular expressions (javascript).cson
These are also character classes:
- \t (horizontal tab)
- \r (carriage return)
- \n (linefeed)
- \v (vertical tab)
- \f (form-feed)
See: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions)
=> Add \t \r \n \v & \f to RegEx character-class scope

grammars/javascript.cson, spec/javascript-spec.coffee
This PR fixes 2 issues with optional and default values when using the param square bracket syntax and when using valid whitespace.
```js
/**
* @param {string} [foo] - optional value
* @param {string} [foo=bar] - default value
*/
```
=> Improve JSDoc support for optional and default values

grammars/javascript.cson, spec/javascript-spec.coffee
This PR adds support for the tilde `~` char in JSDoc types that is used to signify class-specific callbacks http://usejsdoc.org/tags-callback.html
=> Allow tilde char in JSDoc types

grammars/javascript.cson, spec/javascript-spec.coffee
This PR fixes 2 issues with valid syntax that uses square brackets and JSDoc.
=> Improve JSDoc square bracket support

grammars/javascript.cson, spec/javascript-spec.coffee
This PR allows one to use an optional `.` prefix when defining type application with JSDoc.
So we now support: `{Array.<string>}` as well as `{Array<string>}` ((http://usejsdoc.org/tags-type.html)
=> Allow optional prefix with JSDoc's type application

grammars/javascript.cson, spec/javascript-spec.coffee
- Add `@param` synonyms `@arg` and `@argument`
- Remove the hyphen before the description from the capture
See: http://usejsdoc.org/tags-param.html
=> Improve JSDoc grammar

grammars/javascript.cson
This PR adds support for missing JSDoc tags used with Google Closure Compiler:
[`@implicitCast`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#implicitcast)
[`@modifies`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments)
[`@suppress`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#suppress-warninggroup1warninggroup2)
[`@noalias`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#noalias)
[`@nocompile`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nocompile)
=> Add missing JSDoc Google closure tags

grammars/embedded javascript.cson, grammars/javascript.cson, spec/javascript-spec.coffee
When embedded, a </script> tag will break out of the script block even if it would otherwise be in a comment or string.  There's no way to catch when we're embedded with javascript.cson, but we can do it using an injectionSelector.
Supersedes and closes #371.
Blocked on atom/first-mate#78.
Unblocks atom/language-html#90.
=> Return control to language-html when </script> is detected when embedded

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes #452:
```js
import(x) { "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; }
Import(x) { "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; }
```
=> Fix #452: Wrong scopes for methods named "import"

grammars/javascript.cson, spec/javascript-spec.coffee
This is the first of a couple of PRs that add JSDoc support for the [function type](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#function-type).
Since it effects the indentation of quite a few lines it might be easier to review with [whitespace changes off](https://github.com/atom/language-javascript/compare/master...bgriffith:feature/basic-function-jsdoc?expand=1&w=1).
=> Add basic JSDoc function type support

grammars/javascript.cson, spec/javascript-spec.coffee
This PR adds support for [function return type](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#function-return-type) with JSDoc.
=> Add JSDoc support for function return type

.coffeelintignore
Added in 2058cd0, but there isn't a `spec/fixtures` folder (and to my understanding, there never was). This file is just adding clutter.
=> Delete redundant .coffeelintignore file

grammars/javascript.cson
This is such a common trick in JavaScript, and it looks pretty nice as a ligature:
A patched typeface currently can't target `!!` with a ligature, because each `!` is tokenised separately. The scopes are the same, so there's otherwise no outward difference. For that reason, I've not bothered to include a spec; please advise if you'd like one.
=> Allow OpenType ligatures in "double-not" operators

grammars/javascript.cson, spec/javascript-spec.coffee
Two JSDoc-related fixes, both of which are legal syntax:
```js
/**
* @param {String} [name="default value"] Description
* @param {Object} name - Description with {@link link}.
*/
```
**Preview:**
=> Fix quoted defaults / inline links in JSDoc @param lines

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes the issues brought up by @bgriffith in #460, as well as another I noticed while filling out specs:
```js
import { default as alias };
import
{
default
as
alias
};
```
=> Fix #460: Incorrect highlighting for multiline imports

grammars/javascript.cson, spec/javascript-spec.coffee
This PR adds support for [prefixes and suffixes to the function type params](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#variable-parameters) in JSDoc.
Highlighting:
=> Add support for JSDoc function type param prefixes/suffixes

grammars/javascript.cson, spec/javascript-spec.coffee
A bunch of mostly JSDoc-related fixes, plus a keyword-highlighting bug I picked up on when subclassing arrays. You can see them all in one picture:
[As you can see](https://cloud.githubusercontent.com/assets/2346707/21285535/290e55c8-c48f-11e6-8c76-77e316668d7f.png), the above code is perfectly legal JSDoc syntax:
=> Fix various highlighting bugs

snippets/language-javascript.cson
Added a ternary operator snippet that can be accessed with `tern`. This are strongly used in react to control the rendering of two components based on a simple condition.
=> Add ternary operator snippet

grammars/javascript.cson, spec/javascript-spec.coffee
Changed the class assigned to 'const' to use the same syntax class as 'var', and 'let'. 'const' formerly had the modifier class. 
No other alternative designs were discussed in the issue. Was chosen because 'const' should have the same scopes, because it fills the same lexical role as 'let' and 'var' do - named data assignment.
'const', 'let', and 'var' will have the same syntax highlighting.
Since the change is quite minor, their should not be any drawbacks.
Fixes: [https://github.com/atom/language-javascript/issues/471](https://github.com/atom/language-javascript/issues/471)
###Image Before Change
###Image After Change:
=> Changed const to use the same syntax class as var and let.

grammars/javascript.cson, spec/javascript-spec.coffee
Reverts atom/language-javascript#463
@Alhadis, @abe33, @maxbrunsfeld, @bgriffith
Semicolons are optional throughout the entire spec, though they don't visually appear to be.
=> Revert "Fix #460: Incorrect highlighting for multiline imports"

grammars/javascript.cson, spec/javascript-spec.coffee
Both of these lines are valid JSDoc constructs:
~~~js
/**
* @param {Object} [name=Default.value]
* @param {Object} [name=defaultValue]
*/
~~~
A `@param` tag's default-value [accepts anything](http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters) that a [`@type`](http://usejsdoc.org/tags-type.html) parameter does, so whatever's valid as a `@type` is also valid as a default value:
~~~js
/**
* @type {Default.value}
* @type {defaultValue}
*/
~~~
=> Add support for namespaced default values

grammars/javascript.cson
I'm working a lot with SJS files. These are JS files that include some additional proprietary APIs that run on the server-side (predating NodeJS). See https://developer.mozilla.org/en-US/docs/Mozilla/httpd.js/HTTP_server_for_unit_tests#SJS:_server-side_scripts for more
Added `sjs` to the list of supported filetypes
N/A
Package supports more types of jS
sjs is not very widely used. It might overlap with other files that people use in atom?
N/A
=> Add SJS (server-side JavaScript) to filetypes

grammars/javascript.cson, spec/javascript-spec.coffee
Added "source.sql" syntax highlighting for SQL tagged strings.
https://github.com/atom/language-php/blob/master/grammars/php.cson#L1614
=> Add support tagged SQL template strings

snippets/language-javascript.cson
No one
Snippet for `return`. These days is very common to return promises or values (as in functional programming), and I've found very useful the `ret` in language-php snippets
language-php defines other 2 snippets for returning true or false:
```cson
'return false':
'prefix': 'ret0'
'body': 'return false;$0'
'return true':
'prefix': 'ret1'
'body': 'return true;$0'
```
But maybe just one `return $1;` is good enough
New snippet that hope to help everyone
No one
At least, no one
=> return snippet

grammars/javascript.cson, grammars/regular expressions (javascript).cson
Depending on the regular expression engine used, \h does not always
mean the same. With a PCRE engine, it matches white spaces, whereas,
with a Oniguruma engine, it matches hexademical digit characters.
Atom uses an Oniguruma engine, but github.com relies on a PCRE
engine.
None were considered.
Makes the grammar PCRE-compatible, so that it can be used on github.com.
I don't have any way to check these PCRE vs. Oniguruma discrepancies at the moment. I'm working on a new test at the Linguist-level to check for all known discrepancies.
=> Avoid using the ambiguous \h shorthand character

grammars/javascript.cson, spec/javascript-spec.coffee, spec/jsdoc-spec.coffee
So that updating the atom/atom version is easier.
=> Temporarily revert comment scope changes

grammars/javascript.cson, spec/javascript-spec.coffee, spec/jsdoc-spec.coffee
Mostly just a revert of #520.  See #521 for conversation.
=> Use 'punctuation.definition.comment.begin/end.js'

snippets/language-javascript.cson
Added a new `dir` snippet.
No alternates.
Studying and writing JavaScript means frequently use of console. And simple `console.log()` is not always enough to catch anyoing bug or figure out what's going on in your code. I myself often have to use `console.dir()` and frankly speaking i'm tired of typing this every time. So, here is the solution.
No, just a new snippet.
Didn't find any of them.
=> Add 'dir' snippet

grammars/jsdoc.cson
This PR updates the [JSDoc grammar](https://github.com/atom/language-javascript/blob/23fac44/grammars/jsdoc.cson) with new tags added in v3.5.0, and also fixes a few omissions for Closure Compiler related stuff.
The notes of each commit contain details and references:
* [[`7c0699f2e`](https://github.com/atom/language-javascript/commit/753cb5d8aff676d5bff684bb59b1c04)] Add `@polymer` and `@polymerBehavior` JSDoc tags
* [[`6685c1a9c`](https://github.com/atom/language-javascript/commit/6685c1a9c60c60681e865f622f7fea4a8fa58e63)] Allow curly brackets to be used in some JSDoc tags
* [[`1524164e5`](https://github.com/atom/language-javascript/commit/1524164e55879f23a6429941422906fd5bfcebb9)] Add support for JSDoc 3.5.0 tags
=> Update JSDoc grammar with recent additions

grammars/jsdoc.cson, spec/jsdoc-spec.coffee
@Alhadis please review and tell me there's a better solution than this
Fixes #533
=> Fix catastrophic backtracking?

grammars/regular expression replacement (javascript).cson, grammars/regular expressions (javascript).cson
This PR is a follow-up of [`atom/grammar-selector#34`](https://github.com/atom/grammar-selector/pull/34), which patched the grammar selection menu to hide grammars without a defined `name` field. Refer to the PR for rationale and prior discussion.
This package contains two grammars which are (as far as I can tell) only used by `find-and-replace` to highlight input fields when the regex option is active. This should be enough to declare them "internal-use only".
I left JSDoc alone because I'm not 100% sure whether hiding it is the right thing to do. Yes, the JSDoc grammar *is* used indirectly in the same way other "internal-use only" grammars are... however, its presence in the menu is far from conspicuous, as JSDoc is well-known to any JS dev worth their salt. I'll leave it to you to …
=> Hide RegExp-specific grammars from selection menu

grammars/javascript.cson, spec/javascript-spec.coffee
This is legal JS:
~~~js
async function filter(list){
list = doStuff(...await parseList(list));
}
~~~
Currently, `...await` isn't receiving correct highlighting and requires an intervening space character in order for `await` to be scoped properly. This PR fixes that.
=> Allow spreads to precede the `await` operator

grammars/javascript.cson
Adds the Jest Snapshot file extension to the list of Grammar extensions. For more information on the file format see the [Jest documentation](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
It is very easy to create large snapshots. Because of this attempting to tokenize and color the large file could create performance issues for Atom.
=> Add Jest Snapshot File Format

appveyor.yml, grammars/tree-sitter-javascript.cson, package.json
This adds an alternative JavaScript grammar that uses [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript) for parsing instead of [first-mate](https://github.com/atom/first-mate).
=> Add tree-sitter JavaScript grammar

grammars/regular expressions (javascript).cson, spec/javascript-spec.coffee
1. Added support for regular expression lookbehind syntax highlighting, as the ECMAScript proposal has reached [stage 4](https://github.com/tc39/proposals/blob/master/finished-proposals.md), and is considered a 'finished proposal'.
2. Added unit tests for both lookahead and lookbehind syntax highlighting.
The `meta.assertion.look-behind.regexp` scope was chosen so as to be consistent with the existing `meta.assertion.look-ahead.regexp` scope, though technically `meta.assertion.lookbehind.regexp` would have been better, as the term lookahead is used in the ECMAScript language specification with no dash.
Enables custom syntax highlighting of regular expression lookbehind assertions.
There weren't previously any unit tests testing regular expression lookahead/lookbehind highlighting, so …
=> Add regular expression lookbehind highlighting.

grammars/javascript.cson, spec/javascript-spec.coffee
1. Adds support for regular expression `s`(`dotAll`) flag syntax highlighting, as [the ECMAScript proposal](https://github.com/tc39/proposal-regexp-dotall-flag) has reached stage 4, and is considered a ["finished proposal"](https://github.com/tc39/proposals/blob/master/finished-proposals.md).
2. Adds a third scope - `meta.flag.regexp` - to all regular expression flags (no change to existing scopes).
3. Adds unit tests for both single- and multi-flag regular expression syntax highlighting.
The `meta.flag.regexp` scope was chosen instead of `meta.flag.regexp.js` to be consistent with other regular expression scopes like `meta.group.assertion.regexp`.
Adds support for the regular expression `s`(`dotAll`) flag, and enables custom syntax highlighting of all regular expression flags.
There …
=> Add regular expression s flag highlighting.

grammars/javascript.cson, spec/javascript-spec.coffee
1. Adds support for `Promise` method call syntax highlighting.
2. Adds unit tests for both single- and multi-line `Promise` method call syntax highlighting.
Other possibilities were considered in #358 for the `console` and `Math` objects - the solution that was settled on is replicated here for the `Promise` object.
Enables custom syntax highlighting of Promise method calls:
There weren't previously any unit tests testing `Promise` method call syntax highlighting, so there weren't any to test against.
None.
=> Update Promise highlighting.

grammars/regular expressions (javascript).cson, spec/javascript-spec.coffee
1. Adds support for regular expression named capture group and named backreference syntax highlighting, as [the ECMAScript proposal](https://github.com/tc39/proposal-regexp-named-groups) has reached stage 4, and is considered a ['finished proposal'](https://github.com/tc39/proposals/blob/master/finished-proposals.md).
2. Adds unit tests for capture group, non-capture group, named capture group, named backreference and numbered backreference syntax highlighting.
None.
Enables custom syntax highlighting of regular expression named capture groups and backreferences.
There weren't previously any unit tests testing regular expression named capture group or named backreference syntax highlighting, so there weren't any to test against.
None.
=> Add regular expression named capture group highlighting.

grammars/javascript.cson, spec/javascript-spec.coffee
Fixes the highlighting when re-exporting a default export:
```js
export {
default as alias,
} from 'module';
```
Find an alternate regex.
The export will be properly tokenized.
There could be a performance hit with the new regex.
I actually did find one! #271
=> Fix multiline re-export of the default export

grammars/javascript.cson, spec/javascript-spec.coffee
Supports the use case of @iskitz.
Figure out a better way to differentiate division from regex.
ionify and regexes in inline blocks will be tokenized correctly.
I don't think there will be any - all the punctuation I added can't be used for division.
https://github.com/atom/language-javascript/issues/530#issuecomment-341976488
=> Allow more punctuation to precede regexes

grammars/tree-sitter-javascript.cson
Adds the `delete` keyword to the tree-sitter grammar.
None
The `delete` operator is properly highlighted when using tree-sitter parser.
None
n/a
cc: @maxbrunsfeld
=> add delete keyword to tree-sitter grammar

grammars/tree-sitter-javascript.cson
Adds tree-sitter syntax highlighting for `++` and `--` operators.
Don't highlight these things.
These operators will be highlighted and it will match the way the text-mate grammar highlights them.
Someone doesn't want these highlighted 😄 
n/a
cc: @maxbrunsfeld
=> add operator highlighting for ++ and --

grammars/tree-sitter-javascript.cson
Adds syntax highlighting for the rest/spread operator (`...`).
n/a
Spread operator is highlighted.
You don't want the spread operator highlighted.
=> add spread operator syntax

grammars/tree-sitter-javascript.cson
Not sure how I missed this one earlier... whoops. Adds `/` to the list of operators in the grammar.
Leave it out.
Division operator will be styled consistently with other mathematical operators.
None.
None.
cc: @maxbrunsfeld
=> add / to operators list

grammars/tree-sitter-javascript.cson, lib/main.js, package.json
This PR uses Atom's [new system](https://github.com/atom/atom/pull/17551) for handling injected languages with Tree-sitter. It allows syntax highlighting for:
* JavaScript inside of `script` tags in HTML files
* HTML inside of certain template strings in JavaScript files
* EJS templates
=> Make use of Tree-sitter grammar injection

grammars/tree-sitter-javascript.cson
Fixes #558 
Change the TreeSitter grammar to highlight CONSTANT_VARIABLES, ClassNames, and some common built-in variable names (`global`, `module`) with special classes.
:pear:d @maxbrunsfeld
=> Highlight special variables, CONSTANT_VARIABLES, and ClassNames

grammars/tree-sitter-javascript.cson
Specifically:
- Don't mark CapitalizedWords as constructors in call expressions where they aren't invoked with `new`. In that case, use `entity.name.type.instance.meta.constructor`
- Do highlight `window` and `document`. Stuff just looks dull otherwise.
Re: https://github.com/atom/atom/issues/17811
=> Match the textmate styling a little more closely.

grammars/tree-sitter-javascript.cson
Generator function names were not given scopes; now they are.
It seems [`language-typescript`](https://github.com/atom/language-typescript/blob/master/grammars/tree-sitter-typescript.cson) could also benefit from this.
=> Colour generator functions too

grammars/tree-sitter-javascript.cson
Refs https://github.com/atom/atom/issues/18307
* Component names in JSX are now colored like other constructors
* Curly braces in JSX are now colored like the interpolation delimiters `${` and `}` in template strings
=> Fix some JSX scope mappings

grammars/tree-sitter-javascript.cson
Super was unscoped in tree-sitter because the syntax-tree is `call_expression > super` instead of `call_expression > identifier`
With this PR we scope it as `support.function` so it looks the same as `require`.
/cc: @maxbrunsfeld
=> Scope super as support.function

grammars/javascript.cson, spec/javascript-spec.coffee
=> Add support for gql template literal

grammars/tree-sitter-javascript.cson
Scope `jsx_self_closing_element` as `meta.class` if they match the regex. Same as `jsx_closing_element` and `jsx_opening_element`.
`jsx_self_closing_element` will be highlighted the same as the `jsx_closing_element` and `jsx_opening_element` elements. With the `meta.class` scope if they match the `^[A-Z]` regex.
Someone wants self closing elements to be `entity.name.tag` even when they match the regex.
/cc: @maxbrunsfeld Found myself writing some JSX and saw this so opening a PR to fix it.
=> Self closing elements can also be meta.class

grammars/tree-sitter-javascript.cson
The comma and period currently both have the same `meta.delimiter` scope, which makes it impossible to style them differently. This change modifies both so that they can be distinguished: `meta.delimiter.comma` and `meta.delimiter.period`.
The `keyword.operator.accessor` scope would be more appropriate for the period as per the ECMAScript specification, but that might not work well with some themes.
It becomes possible to apply different styles to commas and periods.
=> Distinguish between commas and periods.

grammars/tree-sitter-javascript.cson
Folding `case` statements was not included in the tree-sitter grammar. With this PR we add a fold rule that folds up until the `break_statement` or folds the entire case if there isn't a `break_statement`.
All cases folded:
Some cases unfolded:
Fold everything including the `break_statement`
* You can fold case
* You can see fall through structure very quickly when folded
Someone wants the entire case to be folded including the break and we don't allow it!
None
=> Fold rules for switch_case

grammars/tree-sitter-javascript.cson
Fixes https://github.com/atom/language-javascript/issues/619
Fixes https://github.com/atom/language-javascript/issues/617
Fixes https://github.com/atom/language-javascript/issues/616
Fixes https://github.com/atom/language-javascript/issues/566
/cc: @maxbrunsfeld
=> Add more scopes to the tree-sitter grammar

grammars/tree-sitter-javascript.cson, grammars/tree-sitter-jsdoc.cson, lib/main.js, package.json
Fixes #600 
When we introduced Tree-sitter, we removed the feature of syntax-highlighting JSDoc comments in JavaScript. This PR adds back JSDoc highlighting using a new Tree-sitter parser: [tree-sitter-jsdoc](https://github.com/tree-sitter/tree-sitter-jsdoc).
This adds many more injections in some JavaScript files, so it may affect performance. In the course of adding this, I already found and fixed two performance bottlenecks related to large numbers of language injections:
* https://github.com/atom/atom/pull/18435
* https://github.com/atom/atom/pull/18438
/cc @Ben3eeE
=> Add JSDoc injection w/ tree-sitter-jsdoc

grammars/tree-sitter-javascript.cson
* Add a scope for formal parameter identifiers that is not styled in one-syntax
* Add `unquoted` to `member_expression > identifier`
* Add `component.jsx` to jsx components
* Add `spread` scope to the spread operator
* Scope some variables as `support.variable.dom`
Users of `language-babel` will see more familiar highlighting or can configure it to be more familiar and still get the benefits of tree-sitter parsers
* `support.variable.dom` has the `variable` class so these will be highlighted as red in one-syntax. This is what TextMate scoped them as …
=> Change scopes in comparison to language-babel

lib/main.js
This change fixes #634 which reports that the Tree-Sitter JavaScript grammar does not correctly highlight tagged template injections which have function parameters, such as those used in the [Styled Components](https://www.styled-components.com/) library.  The fix enables tagged template injections to be highlighted correctly when the template invocation includes function arguments.
**Before**
**After**
This is the simplest design that enables any tagged template literal to be called with arguments and then have a language injection to be applied.
CSS syntax inside of `styled` template literals with function arguments (`styled(Button)`) is now highlighted correctly.
None
Fixes #634
=> Allow tagged template injections to accept function parameters

grammars/tree-sitter-javascript.cson
Tree-sitter currently treats all comments as `comment.block`. However, the distinction between block and line can be useful
For example, I'm trying to write a script that auto-comments newlines when created inside a line comment. I don't want it to do this inside a block comment, but it's difficult to tell which it is using the provided scopes. E.g., the desired behaviour is
```
// some |text
// some
// |text
```
but in an actual block comment, we would get
```
/*
some |text
*/
/*
some
// |text
*/
```
The Tree-sitter grammar could differentiate comments. …
=> Differentiate line and block comments

grammars/javascript.cson, spec/javascript-spec.coffee, spec/jsdoc-spec.coffee
GitHub's [Linguist](https://github.com/github/linguist), which is used for syntax highlighting on GitHub.com, currently uses this grammar for highlighting Javascript and JSX. For quite some time now, users have experienced the problem where the presence of an apostrophe within JSX causes the syntax to be highlighted in red as an error:
@Alhadis [proposed](https://github.com/github/linguist/issues/3044#issuecomment-459651756) the solution of removing the "rule which highlights unterminated strings as errors" which @50Wliu suggested would probably be fine …
=> Remove invalid string highlighting from TextMate grammar

grammars/tree-sitter-javascript.cson
case statements in javascript are parsed as:
switch_statement > switch_body >switch_case
Default case statements in javascript are parsed as:
switch_statement >switch_body > switch_default
This PR adds `switch_default` to the folding rules so default can be folded with the same rule as case.
N/A
Consistent folding rules for switch statements
Someone likes unfoldable default and will open an issue that they can now fold it
N/A
```js
const fun = () => {
switch (variable) {
case DO_STUFF:
do_stuff();
break;
case DO_OTHER_STUFF:
do_other_stuff();
test(); …
```
=> Allow folding switch_default

snippets/language-javascript.cson
Fixes https://github.com/atom/language-typescript/issues/29
Flow files are actually handled by `language-typescript`, but the JS snippets should all be applicable in that context. To address this, I add `.source.flow` to the selector for the JS snippets in this PR.
=> Allow JS snippets to be used in Flow files

grammars/tree-sitter-javascript.cson
This PR tokenizes single (paren-less) parameters for arrow functions. The first-mate source.js grammar already did this, while the current tree-sitter grammar does not. Consider the following screenshots:
**Current tree-sitter grammar:**  
**Tree-sitter grammar with this PR applied:**  
**Current first-mate grammar:**  
A different selector could be used or the precedence of the grammar rule could be adjusted, if need be. Although this seems to work without any repercussions.
More consistent coloring for arrow function parameters, whether or not you use …
=> Colorize arrow function parameters without parens

grammars/tree-sitter-javascript.cson
Currently, the tree-sitter grammar does not colorize rest parameters in functions. This is in contrast to the first-mate grammar, which _does_ colorize such parameters. This PR colorizes rest parameters as `formal-parameter.identifier`, like other function parameters.
**Before:**  
**After (with these PR changes):**  
**Current first-mate grammar:**  
The selector was chosen because it is similar to the existing selector for formal parameters, so it should have no conflicts with other grammar rules.
Rest parameters are now treated just like other formal …
=> Colorize rest parameters like other formal parameters

grammars/tree-sitter-javascript.cson
A recent update to https://github.com/tree-sitter/tree-sitter-javascript restructured the way function declarations are constructed in the syntax tree. This change is not present in the latest stable Atom (v1.38.0 at the time of this writing), but is present when I forked language-javascript (v0.132.0 at the time of this writing).
In effect, when I cloned and linked `language-javascript`, the names for function declarations are no longer colorized.
**Current:**  
This PR restores colorization for function declaration names, according to the new syntax …
=> Fix lost colorization of function declaration names

snippets/language-javascript.cson
Following the for...of reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of
The variable declaration with "var" is missing and the autogenerated snippet produces a ReferenceError
if the variable used in the for is not declared previously in the code.
The forof autocomplete snippet can be used safely.
If the user wants to use an already declared variable, the declaration with "var" in the for has to be removed manually. 
https://github.com/atom/language-javascript/issues/596
=> Fix for...of autocomplete, variable declaration

snippets/language-javascript.cson
It is the simple addition of a single snippet. I did not find tests for these in previously merged commits of the same nature.
I could instead use an anonymous function instead of arrow notation, but after a quick check on `caniuse.com` i decided against it.
sanity++
Not all browsers may support arrow notation
=> Add a 'forEach'  snippet

grammars/javascript.cson
I have to use .cjs extensions, but atom doesn't recognise them as js language, so I added the extension
=> add cjs file extension to grammars

grammars/javascript.cson, grammars/tree-sitter-javascript.cson
None
See pull #681 
Adds globalThis, self, and frames
Both files are now consistent compared to the last pull
Note that globalThis is not in support.variable.dom, but rather support.variable, as it refers to the globalThis (which doesn't have to be Window). See MDN for this one.
I find putting globalThis in the same section as "module" and "exports" pretty strange though.
=> Html update

.github/workflows/ci.yml, package.json
`^version` means install any version that is compatible with the range.
This means npm can even install tree-sitter-javascript version 0.15
since in semver 0.15 should be compatible with 0.19. tree-sitter seems
to have broken semver. 0.15 is not compatible with 0.19
=> Install the exact version instead of range
